In [13]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder
import numpy as np
url = "https://raw.githubusercontent.com/100daysofml/100daysofml.github.io/refs/heads/main/content/Week_03/wine_quality.csv"
wine_data = pd.read_csv(url)

#Replace missing values
wine_data.fillna(wine_data.mean(), inplace=True)

#Count missing values 
df.isnull().sum()

#describe data for review
wine_data.describe()

#clip outliers
Q1 = wine_data.quantile(.25)
Q3 = wine_data.quantile(.75)
IQR = Q3 - Q1
wine_data_clipped = wine_data.clip(lower=Q1 - 1.5*IQR, upper=Q3 + 1.5*IQR, axis=1)

#describe data for review
wine_data_clipped.describe()


fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1143.000000       1143.000000  1143.000000     1143.000000   
mean        8.269991          0.529884     0.268290        2.323141   
std         1.630215          0.174273     0.196425        0.609600   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.392500     0.090000        1.900000   
50%         7.900000          0.520000     0.250000        2.200000   
75%         9.100000          0.640000     0.420000        2.600000   
max        12.100000          1.011250     0.915000        3.650000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1143.000000          1143.000000           1143.000000  1143.000000   
mean      0.080926            15.463255             45.127297     0.996725   
std       0.017753             9.725860             29.974752     0.001843   
min       0.040000             1.000000              6.000000     0.992157   
25%       0.070000             7.000000             21.000000     0.995570   
50%       0.079000            13.000000             37.000000     0.996680   
75%       0.090000            21.000000             61.000000     0.997845   
max       0.120000            42.000000            121.000000     1.001257   

                pH    sulphates      alcohol      quality           Id  
count  1143.000000  1143.000000  1143.000000  1143.000000  1143.000000  
mean      3.310105     0.648994    10.437854     5.652668   804.969379  
std       0.151786     0.136473     1.068643     0.779335   463.997116  
min       2.912500     0.330000     8.400000     3.500000     0.000000  
25%       3.205000     0.550000     9.500000     5.000000   411.000000  
50%       3.310000     0.620000    10.200000     6.000000   794.000000  
75%       3.400000     0.730000    11.100000     6.000000  1209.500000  
max       3.692500     1.000000    13.500000     7.500000  1597.000000

In [16]:
#normalize features, drop quality as the target variable 
#use fit_transform on training data, won't use for test data 
scaler = StandardScaler()
wine_data_scaled = scaler.fit_transform(wine_data_clipped.drop('quality', axis=1))

In [21]:
# split the dataset
from sklearn.model_selection import train_test_split

X = wine_data_scaled
y = wine_data['quality']
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [22]:
# train the model
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [23]:
#model evaluation - accuracy score
from sklearn.metrics import accuracy_score

predictions = model.predict(X_test)
print("Accuracy:",accuracy_score(y_test, predictions))

Accuracy: 0.6768558951965066


In [24]:
#model evaluation - confusion matrix 
from sklearn.metrics import confusion_matrix

print("Confusion Matrix:\n", confusion_matrix(y_test,predictions))

Confusion Matrix:
 [[ 0  3  3  0  0]
 [ 0 74 21  1  0]
 [ 0 25 65  9  0]
 [ 0  0 10 16  0]
 [ 0  0  2  0  0]]


In [29]:
#model evaluation - cross validation
from sklearn.model_selection import cross_val_score

# Get scores
cross_val_scores = cross_val_score(model, X, y, cv=5)

# Calculate summary stats
print(f"Cross-Validation Scores: {cross_val_scores}")
print(f"Average CV Score: {cross_val_scores.mean():.3f}")
print(f"Standard Deviation: {cross_val_scores.std():.3f}")
print(f"95% Confidence Interval: {cross_val_scores.mean():.3f} (+/- {cross_val_scores.std() * 2:.3f})")
print(f"Min Score: {cross_val_scores.min():.3f}")
print(f"Max Score: {cross_val_scores.max():.3f}")

Cross-Validation Scores: [0.44541485 0.56768559 0.61135371 0.57894737 0.53508772]
Average CV Score: 0.548
Standard Deviation: 0.057
95% Confidence Interval: 0.548 (+/- 0.113)
Min Score: 0.445
Max Score: 0.611
